### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by ImInTheICU** [Giant427/MovementHandler#1]
I uploaded the animations to roblox and also changed the IDS and its still not animated

**Comment by Giant427** [comment]
- did the camera tween and did the walk speed change?
- were there any errors in the output?

**Comment by ImInTheICU** [comment]
No errors, and the camera does tween it seems its just the animations not working.

**Comment by Giant427** [comment]
The problem must be in the animations then, do you mind sending the URLs of the animation.....?
The animations still work fine for me.

**Comment by ImInTheICU** [comment]
I will in a minute

**Comment by ImInTheICU** [comment]
Sorry im back!
I hade a-lot to do.
I uploaded the animations using the Animation Object inside of animations than i replaced the ID in the animations object with the one i uploaded, still nothing

**Comment by ImInTheICU** [comment]
https://streamable.com/5swhrz
Its safe to say this is need's a update.

**Comment by Giant427** [comment]
> https://streamable.com/5swhrz

not loading
***
are there any errors in the output?

**Comment by ImInTheICU** [comment]
I got the animations working but the system is kinda laughable.
